name: Terraform
on:
  push:
    paths:
      - 'terraform/**'
  pull_request:
    paths:
      - 'terraform/**'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ hashFiles('terraform/.tflint.hcl') }}

      - uses: hashicorp/setup-terraform@v2
      - uses: terraform-linters/setup-tflint@v2

      - name: terraform fmt
        run: terraform fmt -check

      - name: terraform init
        run: terraform init -backend=false

      - name: terraform validate
        run: terraform validate -no-color

      - name: tflint init
        run: tflint --init

      - name: tflint
        run: tflint -f compact
